name: release-clone-solution-to-prod-inputs

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "Solution Name: The name of the solution to import. Always use the solution's name, not its display name"
        required: true
        default: "dd_TeamsTicketDiscussion"

      clone_name:
        description: "Clone Name: The new name of the clone solution. Make sure the solution is branched and clone using DdFunction/CloneSolution"
        required: true
        default: ""

      build_environment_url:
        description: "Build Environment URL: The URL for the environment you're connecting to."
        required: true
        default: "https://lancombuild.crm6.dynamics.com/"

      production_environment_url:
        description: "Production Environment URL: The URL for the environment you're connecting to."
        required: true
        default: "https://lancomprod.crm6.dynamics.com/"

      client_id:
        description: "Client Id: The application ID to authenticate with. This parameter is required when authenticating with Service Principal credentials."
        required: true
        default: "7ba339a2-835a-447b-bb11-6bc41ae72e1d"

      tenant_id:
        description: "Tenant Id: The tenant ID when authenticating with app-id and client-secret."
        required: true
        default: "2cf084a3-792d-48f5-ae56-579c58293b4b"


  release:
    types: [created]

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Pack solution
        uses: microsoft/powerplatform-actions/pack-solution@0.4.0
        with:
          solution-folder: solutions/${{ github.event.inputs.solution_name }}
          solution-file: out/solutions/${{ github.event.inputs.clone_name }}.zip
          solution-type: Unmanaged

      - name: Import solution as unmanaged to build env
        uses: microsoft/powerplatform-actions/import-solution@0.4.0
        with:
          environment-url: ${{ github.event.inputs.build_environment_url }}
          app-id: ${{ github.event.inputs.client_id }}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{ github.event.inputs.tenant_id }}
          solution-file: out/solutions/${{ github.event.inputs.clone_name }}.zip
          force-overwrite: true
          publish-changes: true

      - name: Export solution as managed
        uses: microsoft/powerplatform-actions/export-solution@0.4.0
        with:
          environment-url: ${{ github.event.inputs.build_environment_url }}
          app-id: ${{ github.event.inputs.client_id }}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{ github.event.inputs.tenant_id }}
          solution-name: ${{ github.event.inputs.clone_name }}
          managed: true
          solution-output-file: out/ship/${{ github.event.inputs.clone_name }}.zip

      - name: Upload the ready to ship solution to GH artifact store
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: out/ship/${{ github.event.inputs.clone_name }}.zip

  release-to-staging:
    needs: [convert-to-managed]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Fetch the ready to ship solution from GH artifact store
        uses: actions/download-artifact@v2
        with:
          name: assets
          path: out/release
      - name: Import solution to prod env
        uses: microsoft/powerplatform-actions/import-solution@0.4.0
        with:
          environment-url: ${{ github.event.inputs.production_environment_url }}
          app-id: ${{ github.event.inputs.client_id }}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{ github.event.inputs.tenant_id }}
          solution-file: out/release/${{ github.event.inputs.clone_name }}.zip
          force-overwrite: true
          publish-changes: true
